### ISSUE TITLE
Update to 1.1?

### ISSUE THREAD

**Issue by DeadlyKitten37** [morsk/logi-command#5]
can you please update your other mod to 1.1.
https://mods.factorio.com/mod/NoFreeplayCutscene/discussion/619df6f50b4374ac1bba0c2e
I found a niche issue where 2 mods interact and crash on the start cutscene but work after.
I went there and found that it was never updated :(
I came here because it looked like this was the best place to contact you.

**Comment by morsk** [comment]
Oh, I didn't know that mod was useful anymore as I heard 1.1 made it unnecessary. But I can try updating it.

**Comment by morsk** [comment]
Something's changed about cutscenes, and my method for removing the crash site makes a mess now and leaves weird things on the screen. I am still looking at it, but I don't know if I'll finish.

**Comment by morsk** [comment]
Updated now!

https://mods.factorio.com/mod/NoFreeplayCutscene

**Comment by DeadlyKitten37** [comment]
Thanks
