### ISSUE TITLE
2.0 soon ?

### ISSUE THREAD

**Issue by Fr-Dae** [morsk/logi-command#6]
sooner ?

**Comment by morsk** [comment]
I didn't know anyone used this. I wrote it for a multiplayer community that requested it, but they ghosted the pull request for a month, not even telling me "No," after I spent 40 hours making it for them. It was very sad as I had friends there, and ended up leaving.

I'm sure I can fix it if someone is actually using it! This is a nice surprise.

**Comment by morsk** [comment]
I do have to see how much is replaced by 2.0's logistic groups. I have no idea.

**Comment by morsk** [comment]
I didn't know anyone used this! I wrote it for friends who requested it, then never used it. (I have better friends now.)

I have to see how much of 2.0's "logistic groups" replace this, or make it unnecessary. I have not had time to play 2.0 as all I've done is update mods.

It is a nice surprise to hear someone actually uses this! If I think it's still useful in 2.0 I will update it. I have to research this.

**Comment by morsk** [comment]
Okay, I don't think this is needed at all in 2.0! It even has a solution that uses combinators and blueprints, and is similar.

1. Name the logistics group you're using to request items. I recommend putting your username in it.
2. Make a combinator using the same group.
3. Make a blueprint of the combinator

You can then bring this blueprint into other worlds, and it will bring the logistic group with it. You can use it to request items.

**Comment by Fr-Dae** [comment]
i'm palying with friend with 0 brain cell, so i make loadout for inventory, logistic, quickbar and export it for them, so we have the same layout

for when i change save. borring to remake many request and quickbar. 

it's not just for me, 
```
Downloads
Version 0.6.1 	
factorio 1.1 	
date 3 years ago 	
total 203
```

and you reply for fast than him
https://mods.factorio.com/mod/PersonalLogisticsImportExport/discussion/6722d212e110c7da23813d1d

**Comment by Fr-Dae** [comment]
> Okay, I don't think this is needed at all in 2.0! It even has a solution that uses combinators and blueprints, and is similar.
> 
>     1. Name the logistics group you're using to request items. I recommend putting your username in it.
> 
>     2. Make a combinator using the same group.
> 
>     3. Make a blueprint of the combinator
> 
> 
> You can then bring this blueprint into other worlds, and it will bring the logistic group with it. You can use it to request items.

ok, i need more information about this, maybe a gif or a video ?

**Comment by morsk** [comment]
I agree you need more information about this, but I am not the best person to help. There are 100s of people on Discord or reddit that can help you with Factorio 2.0 features.

If there are no videos, you could make a video after learning about this, to share with other people. I don't make videos and would not be good at this either.
